version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-sakila
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/1_sakila-schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/2_sakila-data.sql
